### ISSUE TITLE
Rendering bug in API doc

### ISSUE THREAD

**Issue by halbmy** [emsig/empymod#115]
The docstrings in the API docs, e.g.
https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.bipole
are erroneously rendered, probably due to some sphinx (or sphinxcontrib) upgrade so that the type is merged to the variable names:
![image](https://user-images.githubusercontent.com/7136401/105090830-388d0d00-5a9f-11eb-96e2-2e568aa25539.png)

**Comment by prisae** [comment]
Thanks @halbmy for reporting, indeed!

I'll have to figure out what the reason is. v2.0.2 seems still to be fine (https://empymod.readthedocs.io/en/v2.0.2), after that it has this error.

It was a long-standing issue with the numpydoc theme and sphinx versions, but I thought it was resolved... oh well.

**Comment by prisae** [comment]
Hm. Locally I don't have it, and on emg3d.readthedocs.io it isn't an issue either, strange.

**Comment by prisae** [comment]
https://github.com/numpy/numpydoc/issues/215

**Comment by prisae** [comment]
This will be fixed by #116 

I have to force RTD to install `sphinx_rtd_theme>=0.5.0`. I don't know why RTD uses such outdated versions by default (e.g., `sphinx<2`.

I should probably move to create the docs with CI and host on the own website instead of RTD... One day in the future.

Thanks again @halbmy !

**Comment by prisae** [comment]
It will not fix `stable`, as this is a release, but `latest` (and the next stable, whenever that will happen...):

https://empymod.readthedocs.io/en/latest/modeller.html#empymod.model.bipole
